name: HunterXHunterPlugin
version: '1.0-SNAPSHOT'
main: org.flashmob.hunterXHunterPlugin.HunterXRunnerPlugin
api-version: '1.21'
authors: [ flashmob ]
commands:
  startgame:
    description: Set weather clear, time set 0, clear achievements, clear inventories, clear items
    usage: /<command>
    permission: op
    permission-message: You lox
  moveto:
    description: Tp to player
    usage: /<command> [player]
  setrole:
    description: Select runner
    usage: /<command> [hunters|runners]
    permission: op
  getcompass:
    description: Get hunter compass
    usage: /<command>
  suicide:
    description: Suicide
    usage: /<command>
  listrole:
    description: Players in role
    usage: /<command> [hunters|runners]
  hunterchat:
    description: Hunter chat
    usage: /<command> text
  devstart:
    description: Dev start game
    usage: /<command>